version: "1"
services:
  nginx:
    build: ./nginx
    ports:
      - "443:443" # HTTPS port
      - "80:80" # HTTP port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
